spring:
  application:
    name: service-auction

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/auction_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

server:
  port: ${AUCTION_PORT:8083}

# TODO: example set
auction:
  default:
    duration: 86400
    min-increment: 1000
    extension:
      enabled: false
      threshold: 30
      duration: 300
      max-extensions: 3
