spring:
  application:
    name: service-bid

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/bid_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

server:
  port: ${BID_PORT:8084}

# TODO: example set
bid:
  idempotency:
    ttl: 300
  retry:
    max-attempts: 3
    backoff-delay: 100
  validation:
    min-amount: 1000
    max-amount: 100000000
